spring:
  profiles:
    default: local
  datasource:
    #jdbc-url: jdbc:mariadb://39.117.246.63:3306/onedb
    jdbc-url: jdbc:log4jdbc:mariadb://39.117.246.63:3306/onedb?allowMultiQueries=true
    username: devman
    password: devman@@1019
    #driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    connection-test-query: SELECT 'local'
  sql:
   init:
    mode: never # Spring Boot >=v2.5.0

## mybatis config
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: true
    call-setters-on-nulls: true


server:
  port: 10011

#logging:
#  #config: classpath:log4j2.xml
#  level:
#    com.solutionil.onebe: debug
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
## Swagger doc
springdoc:
  version: v1.0.0
  swagger-ui:
    path: /api-docs


---

spring:
  config:
    activate:
      on-profile: develop
  datasource:
    #jdbc-url: jdbc:mariadb://39.117.246.63:3306/onedb
    jdbc-url: jdbc:log4jdbc:mariadb://39.117.246.63:3306/onedb?allowMultiQueries=true
    username: devman
    password: devman@@1019
    #driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    connection-test-query: SELECT 'local'
  sql:
   init:
    mode: never # Spring Boot >=v2.5.0

## mybatis config
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: true
    call-setters-on-nulls: true


server:
  port: 20011

#logging:
#  #config: classpath:log4j2.xml
#  level:
#    com.solutionil.onebe: debug
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
## Swagger doc
springdoc:
  version: v1.0.0
  swagger-ui:
    path: /api-docs
